"""empty message

Revision ID: 38a93a71a965
Revises: 
Create Date: 2023-05-26 22:53:02.767455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a93a71a965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.drop_index('student_class')
        batch_op.drop_index('student_marks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.create_index('student_marks', ['student_marks'], unique=False)
        batch_op.create_index('student_class', ['student_class'], unique=False)

    # ### end Alembic commands ###
